INSERT INTO Doenca (nome)
VALUES ("HIV"),
("Hepatite pós 10 anos de idade"),
("Malária"),
("Chagas"),
("Enxerto de duramater"),
("Câncer gerais ou Leucemia"),
("Problemas de pulmão, coração, rins ou fígado"),
("Diabético com complicações vasculares ou em uso de insulina"),
("Tuberculose extra-pulmonar"),
("Elefantíase"),
("Hanseníase"),
("Calazar (leishmaniose visceral)"),
("Leishmaniose tegumentar ou cutânea"),
("Esquistossomose hepatoesplênica"),
("Doenças que gerem inimputabilidade jurídica"),
("Brucelose"),
("Transplante de órgãos ou de medula"),
("Mal de Parkinson");